#############################################################
#
# Makefile for intel x86_64 compilers
#
# Alexander Soudackov, The Pennsylvania State University
# July 1, 2010
#
#############################################################

ARCH = intel_11.1-x86_64
FC = ifort
# Important: MODFLAG must have a trailing blank
MODFLAG = -module 
BACKSLASH = -assume nobscc
NOBACKSLASH = -assume bscc
F90FLAGS = -fast -fast-transcendentals
F77FLAGS = -fast -fast-transcendentals
LDFLAGS	= 
