#############################################################
#
# Makefile for GNU gfortran compiler
#
# Alexander Soudackov, The Pennsylvania State University
# January 4, 2011
#
#############################################################

ARCH = gfortran_4.1.2_x86_64
FC = gfortran
# Important: MODFLAG must NOT have a trailing blank
MODFLAG = -J
BACKSLASH = -fno-backslash
NOBACKSLASH = -fbackslash
F90FLAGS = -O3 -ffree-form -ffree-line-length-none
F77FLAGS = -O2 -ffixed-form
LDFLAGS =
