#############################################################
#
# Makefile for PGI fortran compiler
#
# Alexander Soudackov, The Pennsylvania State University
# December 5, 2003
#
#############################################################

ARCH = pgi-x86_64
FC      = pgf90
MODFLAG = -module
BACKSLASH = -Mbackslash
NOBACKSLASH = -Mnobackslash
F90FLAGS = -fast -Mipa=fast
F77FLAGS = -fast -Mipa=fast
#F90FLAGS = -g -C
#F77FLAGS = -g -C
LDFLAGS =
