#!/bin/sh
#

#-- help
if [ x$1 == x ]; then
    echo "================================================================================="
    echo "Synopsis:"
    echo $0 "<list of compilers>"
    echo "---------------------------------------------------------------------------------"
    echo "Compilers:"
    echo "intel       (Intel Fortran90 compiler 2011_sp1.7.256 with sequential MKL libraries)"
    echo "intel.omp   (Intel Fortran90 compiler 2011_sp1.7.256 with multi-threaded MKL libraries)"
    echo "intel.debug (Intel Fortran90 compiler 2011_sp1.7.256 with debug options enabled)"
    echo "pgf90       (PGI Fortran90 compiler 9.0.2)"
    echo "pgf90.debug (PGI Fortran90 compiler 9.0.2 with debug options enabled)"
    echo "gfortran    (GNU Fortran90 compiler, gcc 4.1.2"
    echo "================================================================================="
    exit 0
fi

if [ -e "Rebuild.log" ]; then
   rm -f Rebuild.log
fi

if [ -e "Rebuild.err" ]; then
   rm -f Rebuild.err
fi

for compiler in $*
do
   if [ -e "Makefile.${compiler}" ]; then
      ln -s -f Makefile.${compiler} Makefile.machine
      echo "]===>"
      echo "]===> " ${compiler}
      echo "]===>"
      make clean
      time make all 2>> Rebuild.err
      echo -e "\a"
      echo `date '+%a %D at %r'` ": building with " ${compiler} " is done!" >> Rebuild.log
   fi
done

if [ -s "Rebuild.err" ]; then
   echo "There might have been warnings and/or errors: check Rebuild.err!"
   echo "There might have been warnings and/or errors: check Rebuild.err!" >> Rebuild.log
else
   echo "No warnings or errors!"
   rm -f Rebuild.err
fi

echo -e "\a"

# copy the executables to shscluster2
echo
echo -n "===> copying executables to shscluster2 ... "
cp -f ../bin/*.x /home64/souda/PCET/pcet5/bin
echo -e "Done \a"

echo "Executables were copied to /home64/souda/PCET/pcet5/bin" >> Rebuild.log
echo -e "\a"
